training_args:
  output_dir: outputs
  num_epochs: 100

  learning_rate: 5e-6
  lr_scheduler_type: constant_with_warmup
  lr_warmup_steps: 500

  train_batch_size: 4
  eval_batch_size: 4
  data_loader_num_workers: 8

  eval_steps: 1000

  gradient_accumulation_steps: 1
  logger: wandb
  mixed_precision: fp16
  checkpointing_steps: 1000
  resume_from_checkpoint: latest

training_module:
  _target_: mugen.trainingmodule.vae.VAETrainingModule
  pretrained_name_or_path: stabilityai/sd-vae-ft-mse
  freeze_encoder: true
  use_ema: true
  input_key: image
  lpips_config:
    disc_start: 50001
    kl_weight: 0.000001
    disc_weight: 0.5

datamodule:
  _target_: mugen.datammodules.CaptionImageFolderDataModule
  data_dir: /work/hpc/iai/hoang/waiffusion/data/genshin-impact/extracted
  resolution: 256
